### ISSUE TITLE
Include more information about possible attack vectors and their mitigations

### ISSUE THREAD

**Issue by pangolingo** [ngrok/webhooks.fyi#26]
This website was posted on Hacker News, and there was an excellent comment posted about attack vectors - particularly timeout attacks and private IP attacks. I'd love learn more about these attacks in the Security section of this site, focusing on how to allow users to configure their webhook URLs.

https://news.ycombinator.com/item?id=32518208
Posted by [cuu508](https://news.ycombinator.com/user?id=cuu508) on 2022-08-19

> There are some interesting attack vectors to be aware of if you run a service where users can define webhooks, and your service will will call the user-defined webhooks to notify about certain system events. In my case, a monitoring service which can send notifications by calling user-defined webhook.
> * Timeouts: the user can set up a webhook receiver that takes very long to generate a response. Your service must be able to deal with that.
> * Timeouts (slowloris): the webhook target could be sending back one byte at a time, with 1 second pauses inbetween. If you are using, say, the "requests" python library for making HTTP requests, the "timeout" parameter will not help here
> * Private IPs and reserved IPs: you probably don't want users defining webhooks to http://127.0.0.1:<some-port>/ and probing your internal network. Remember about private IPv6 ranges too
> * Domains that resolve to private IPs: attacker could set up foo.com which resolves to a private IP. It is not enough to just validate webhook URLs when users set them up.
> * HTTP redirects to private IPs. If your HTTP client library follows HTTP redirects, the attacker can set up a webhook endpoint that redirects to a private IP. Again, it is not enough to validate the user-supplied URL.
> * Excessive HTTP redirects. The attacker can set up a redirect loop - make sure this does not circumvent your timeout setting.

**Comment by sudobinbash** [comment]
Great call @pangolingo . Thanks for sharing. I'll work on incorporating this.
