### ISSUE TITLE
Detail the OpenID spec/webhook standardization effort

### ISSUE THREAD

**Issue by caseysoftware** [ngrok/webhooks.fyi#36]
https://openid.net/2021/08/24/shared-signals-an-open-standard-for-webhooks/

**Comment by sudobinbash** [comment]
Included under standards alongside the HTTP Signatures spec. 

**One note**: the OpenID Spec focuses on using webhooks only for security solutions to notify each other of security events. So, not applicable to other use-cases like communications, payments, martech, etc.
