### ISSUE TITLE
Accidentally imported Tailwind's license

### ISSUE THREAD

**Issue by gene1wood** [ngrok/webhooks.fyi#46]
It looks like in #3 the Tailwind license document was accidentally imported

https://tailwindui.com/license

https://github.com/ngrok/webhooks.fyi/blob/main/LICENSE.md

I suspect you want to assert your own intentional license for the content on the webhooks.fyi site. The license as it is makes no sense since it's for another product.

**Comment by sudobinbash** [comment]
dang! Great call @gene1wood ! Fixed <3

**Comment by gene1wood** [comment]
Fixed in #47
