### ISSUE TITLE
Propose to add asymmetric caveat - signing/verifying is computationally expensive

### ISSUE THREAD

**Issue by nickrobillard** [ngrok/webhooks.fyi#49]
RSA signing and verifying are significantly more expensive than symmetric encryption (like AES).  This can be problematic for high throughput systems. Signing operation can introduce a bottleneck in sender's infra.

**Comment by sudobinbash** [comment]
Great call @nickrobillard . 
Will add that. Thanks for the contribution <3

**Comment by sudobinbash** [comment]
Heyo @nickrobillard . Thanks for contributing to webhooks.fyi.
I just added the performance concern to our pages! 
Feel free to send me a PR if I didn't do justice to it.

Thanks again for the contribution! <3333
