### ISSUE TITLE
Propose to add CNCF CloudEvents webhook standards

### ISSUE THREAD

**Issue by gowrizrh** [ngrok/webhooks.fyi#51]
This is a proposal to add CloudEvents under the "Standardisation Efforts" section.

CloudEvents is a CNCF incubating project.

https://cloudevents.io

> CloudEvents is a specification for describing event data in common formats to provide interoperability across services, platforms and systems.

It provides specification on message modelling and event payload design multiple protocols from AQMP to HTTP and HTTP Webhooks.

This could also cover a fair bit on #33

I'll be happy to contribute to this one.

**Comment by sudobinbash** [comment]
Thanks for sharing @gowrizrh :)

Any contribution is welcome!

I started digging thru cloudevents and [found this](https://github.com/cloudevents/spec/blob/main/cloudevents/http-webhook.md). Is this a good representation of how cloudevents aims to help on webhooks?

If yes, I'll include that on the standardization effort.

**Comment by gowrizrh** [comment]
That's right. It also might be worth reading through the the [main spec](https://github.com/cloudevents/spec/blob/main/cloudevents/spec.md) which should cover topics around event / payload schemas.

The webhooks specification you linked should be an extension of the main spec with more things covering rate limiting and retries.

**Comment by sudobinbash** [comment]
Hi @gowrizrh . I added CloudEvents to the standardization efforts.
Feel free to send me a PR in case you feel I didn't do justice to the project. 

Thanks again for the contribution and for making the world a better place for webhooks! <3 

**PS**: Are you in the CloudEvents working group?

**Comment by gowrizrh** [comment]
Thank you 😀

No I'm not in the working group

**Comment by embano1** [comment]
Just found this thread and will probably file another PR to update the section. E.g. CE v1 is finalized and stable. Also, CE offers several benefits, including SDKs, transport bindings (Kafka, RabbitMQ, HTTP, etc.) and encoding formats (JSON, Avro, Protobuf) which developers can take advantage of instead of reinventing the wheel (error-prone bespoke formats and SDKs).
