### ISSUE TITLE
Add information in replay prevention about idempotency

### ISSUE THREAD

**Issue by jsgoupil** [ngrok/webhooks.fyi#52]
Great website! Love the completeness.
It would be interesting to add information about idempotency in your replay prevention page.

Some web hook will send you an ID that is guaranteed to be unique on replay. Very useful to avoid doing work twice. This is too often forgotten by the consumer.

**Comment by sudobinbash** [comment]
Yes, @jsgoupil . Great call.
Its also nice to bring that alongside the trade offs of idempotency (keep a track record of requests already sent).
I'll work on that.

Thanks for contributing <3

**Comment by sudobinbash** [comment]
Hi @jsgoupil . Thanks for contributing to webhooks.fyi.
I just added webhook ids to replay prevention <3 
Feel free to send me a PR if I didn't do justice to it.
